name: defifundr
regions:
  - fra
services:
  - name: api
    instance_type: nano
    envs:
      - key: DB_SOURCE
        value: postgresql://DATABASE_USER:DATABASE_PASSWORD@DATABASE_HOST:DATABASE_PORT/defi?sslmode=disable
      - key: TOKEN_SYMMETRIC_KEY
        value: 12345678901234567890123456789012g
      - key: ENVIRONMENT
        value: production
      - key: HTTP_SERVER_ADDRESS
        value: :8080
    ports:
      - port: 8080
        protocol: http
    routes:
      - path: /
        port: 8080
    dockerfile:
      path: Dockerfile
      target: production
  
  - name: postgres
    instance_type: nano
    envs:
      - key: POSTGRES_USER
        value: root
      - key: POSTGRES_PASSWORD
        value: secret
      - key: POSTGRES_DB
        value: defi
    ports:
      - port: 5432
    image: postgres:15-alpine
    volume:
      - name: postgres-data
        mount_path: /var/lib/postgresql/data

volumes:
  - name: postgres-data
    type: persistent
    size: 5Gi