name: Bug Report
description: File a bug report to help us improve the application
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us address the issue.

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: e.g., v1.0.2
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where is this bug occurring?
      options:
        - Production
        - Staging
        - Development
        - Local Environment
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser & Version
      description: If applicable, what browser and version are you using?
      placeholder: e.g., Chrome 98.0.4758.102, Firefox 97.0.1
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., Windows 11, macOS 12.2, Ubuntu 20.04
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug in detail. What did you expect to happen and what actually happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Provide clear steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem (drag and drop images here)

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug's impact?
      options:
        - Critical (Application crash, data loss)
        - High (Major functionality broken)
        - Medium (Feature partially working)
        - Low (Minor issue, cosmetic)
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always
        - Often
        - Sometimes
        - Rarely
        - Only once
    validations:
      required: true

  - type: checkboxes
    id: verification
    attributes:
      label: Verification
      description: Before submitting, please verify that you have done the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have tested with the latest version available
          required: true
        - label: I have included all information necessary to reproduce the bug
          required: true

  - type: markdown
    attributes:
      value: |
        ## Additional Information
        Add any other context about the problem here that might help us solve it faster.