blank_issues_enabled: false
contact_links:
  - name: DefiFundr Backend Repository
    url: https://github.com/DefiFundr-Labs/defifundr_backend
    about: Ask questions and discuss with other community members
  - name: Documentation
    url: https://github.com/DefiFundr-Labs/defifundr_backend/blob/main/README.md
    about: Check the documentation first to see if your question is already answered